### ISSUE TITLE
open ai key 에 대한 sam 환경 변수 추가

### ISSUE THREAD

**Issue by hyejungg** [hyejungg/ai-news-noti-bot#98]
1번 
기본으로 open api key를 데이터랩껄 쓰는데, 특정 경우에만 다르게 실행하고 싶을 수가 있잖아요 ?! 
그래서 생각한 방법은 직접 워크 플로우를 실행시킬 때 `open_api_key`를 같이 파라미터로 받아서 그 step인 경우에 override 하기 어떠신가요?? (아래는 되는진 모르겠지만 저런 느낌?!)
```
workflow_dispatch:
    inputs:
      branch:
        description: '배포할 브랜치'
        required: true
        default: 'main'
      api_access_key:
        description: 'API 액세스 키'
        required: true
        type: string

jobs:
  deploy-ai-news-agent-stack:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
    steps:
        ....

      - name: Use API Access Key
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.api_access_key }}" ]; then
            echo "API_KEY=${{ github.event.inputs.api_access_key }}" >> $GITHUB_ENV
          else
            echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          fi
```

2번 
변경없이 콘솔에서 환경변수를 직접 추가해도 수정하거나 다음 배포 전까지는 적용될텐데 그 방법을 쓰는것도 좋아보여요
